Order-Item Deleted with a refill date in the past
dscsa/pharmacy pull request #172
Opened 2021-04-13 20:33 UTC by Hobstweedl

https://app.asana.com/0/534557523548031/1199671181039610

I think the idea here is to create a SF task if there is an item being deleted when its still set to autofill. Is there a more appropriate subject and event title that should be used?

2021-04-14 19:51 UTC, thehandcoder requested changes

2021-04-14 19:51 UTC, thehandcoder commented on updates/update_order_items.php
> +        strtotime($item['refill_date_default']) < time() &&
I think you could use refill_date_next here instead of checking default and manual.  Refill_date_next should be the correct data.  It is a combination of default and manual.

2021-04-14 19:51 UTC, thehandcoder commented on updates/update_order_items.php
> +        AuditLog::log($salesforce['body'], $item);
Audit::log entries are meant to be human readable history of events.  The Salesforce body is more a script.  You probably want it to be something like 'Deleting rx#{}, but it is currently set to autofill and  it's refill date is invalid.'

2021-04-14 19:51 UTC, thehandcoder commented on updates/update_order_items.php
> +        strtotime($item['refill_date_default']) < time() &&
I believe you've missed the point of this alert.  We are wanting to trigger the alert when it's on autofill and the refill_next data is invalid.  If you read the description and the comments you'll get a better understanding of what want to happen.

2021-04-15 15:03 UTC, Hobstweedl commented
@thehandcoder I made the updates and changed the wording on some of the message. This is very similar to the other salesforce message that is sent out below around on line 306. Is there any concern about both of these messages being sent out together when `refill_date_manual` is null and `refill_date_first` is set?

2021-04-15 15:04 UTC, Hobstweedl commented on updates/update_order_items.php
> +            "When would you like {$item['drug_name']} on Order {$invoice_number} to be filled or should we take it off autofill" :
Is this the right language to be using for these messages?

2021-04-15 15:24 UTC, thehandcoder commented on updates/update_order_items.php
> +            "When would you like {$item['drug_name']} on Order {$invoice_number} to be filled or should we take it off autofill" :
The sales force events are often script like.  A tech might use the script as they contact a client.  My comment was more about the audit log.  That is a different think entirely.  The Audit log is more like a history of what happened when.  It's okay for the salesforce body to be more a script a user might read and the audit log to be more a statement of what happened.

2021-04-15 21:16 UTC, thehandcoder approved these changes

2021-04-16 15:04 UTC, merged