Patient Matching update and quick cli tool
dscsa/pharmacy pull request #181
Opened 2021-04-21 14:35 UTC by Hobstweedl

2021-04-21 15:24 UTC, thehandcoder requested changes

2021-04-21 15:24 UTC, thehandcoder commented on helpers/helper_matching.php
> -            $mysql = GoodPill\Storage\Goodpill::getConnection();
This would handle if there were 10 users that had the sampe id, your change only updates the current user, so it doesn't fix the problem.

2021-04-21 15:24 UTC, thehandcoder commented on helpers/helper_matching.php
> +            $body = "patient_id_cp {$patient_match['patient_id_cp']} was updated to $patient_id_cp. Are there any invoices that need to be updated?";
This message doesn't include near enough details.  It should include:
* the patient label
* the wc_ids for any old patches to the patinet_id_cp
* the wc_id of the current match
* the cp_id of the current match

The message should also be associated to the patient properly using the patient label

2021-04-21 15:24 UTC, thehandcoder commented on helpers/helper_matching.php
> +            wc_upsert_patient_meta(
We should use a for loop here.  As I'm looking through this we should probably add a step so that we mark any wc users that don't match the specified wc_id are also marked as inactive in woocommerce.

2021-04-21 15:24 UTC, thehandcoder commented on helpers/helper_matching.php
> +                'patient_id_cp' => $patient_id_wc,
this should be patien_id_wc

2021-04-26 15:54 UTC, thehandcoder requested changes

2021-04-26 15:54 UTC, thehandcoder commented on helpers/helper_matching.php
> +function force_match(int $patient_id_cp, int $patient_id_wc) : array
The only problem I see is that your are doing this even if match_patient is called with proper existing match.  That was the point of `$patient_match && @$patient_match['patient_id_wc'] != $patient_id_wc`.  If the patient is already proplery matched we don't need to invlaidate any users or change anything, we just need to return true.

2021-04-26 15:54 UTC, thehandcoder commented on helpers/helper_matching.php
> +            if ($meta->user_id !== $patient_id_wc) {
Instead of this if, why don't you add it to the query above?
WpUserMeta::where('meta_key', 'patient_id_cp')->where('meta_value', $patient_id_cp)->where('user_id', '!=', $patient_id_wc)->get();

2021-04-26 15:54 UTC, thehandcoder commented on helpers/helper_matching.php
> +            ->where('user_id', $patient_id_wc)
you could user firstOrNew() and you don't have to do the if

2021-04-26 19:18 UTC, Hobstweedl commented on helpers/helper_matching.php
> +function force_match(int $patient_id_cp, int $patient_id_wc) : array
What about a situation where there are two meta keys for `patient_id_cp` one with the correct id to the wc_user, and one with the wrong wc_user. Would we still want to find and set the mismatched wc_user to inactive?  

I would think you'd always want to find any meta entries where the `patient_id_cp` is associated with the wrong wc user and fix that, otherwise why not just upsert the correct `patient_id_cp` for the wc we want and skip marking any other users inactive? If having wrong meta keys doesn't matter as long as the right one exists, why go through all of the extra work?

2021-04-27 14:40 UTC, thehandcoder commented on helpers/helper_matching.php
> +function force_match(int $patient_id_cp, int $patient_id_wc) : array
I'm not sure.  Part of the entire plan is once the patient is matched, they wouldn't be changed.  ideally once this change is in place there shouldn't ever be mismatches in wc.  We don't enter this routine unless the patient isn't matched.

2021-04-27 15:51 UTC, thehandcoder commented on helpers/helper_matching.php
> +function force_match(int $patient_id_cp, int $patient_id_wc) : array
The idea is if there is a patient_match and the patient match is correct, we don't need to do anything else.  if there isn't a patient match, or we are attempting to force the match, we should do the other stuff.

2021-04-27 16:00 UTC, thehandcoder requested changes

2021-04-27 16:00 UTC, thehandcoder commented on helpers/helper_matching.php
> +        foreach($forced_match_data['invalidated_patients'] as $inactive_patient) {
This foreach is completely fine, but I know you haven't worked with php in a while so I though I'd mention this.  PHP has quite a few functions specifically for working with arrays.  
```
$body .= implode(
    ', ', 
    array_map(
        function($inactive_patient) {return $inactive_patient['patient_id_wc'];} , 
        $forced_match_data['invalidated_patients']
    )
);
```

Would do the same thing but wouldn't leave a dangling comma and wouldn't require you to break the chain of assignments.  Just something you may or may not want to use in the future.

2021-04-27 16:00 UTC, thehandcoder commented on classes/GoodPill/Models/GpPatientsWc.php
> +require_once "dbs/mssql_cp.php";
I see you adding these classes, but didn't see where you were using them.  Am I missing it?

2021-04-27 20:21 UTC, Hobstweedl commented on helpers/helper_matching.php
> +        foreach($forced_match_data['invalidated_patients'] as $inactive_patient) {
Thats really helpful to know actually. I knew that I could probably do something similar with imploding and I've seen a similar thing done elsewhere

2021-05-17 18:00 UTC, merged