Update check_order_status cron with additional log
dscsa/pharmacy pull request #188
Opened 2021-04-26 15:04 UTC by Hobstweedl

Checked printed statements to see how many orders were dispensed or shipped. There should have been at least 2 logs and 2 salesforce notifications going out. I'm adding timestamps right before sending out a log message to see what time the cron is actually running and further debug why no notifications are going out.

2021-04-26 15:24 UTC, thehandcoder requested changes

2021-04-26 15:24 UTC, thehandcoder commented on cronjobs/check_order_status.php
> +    echo sprintf("%s - Send debug message for shipped orders", date('Y-m-d h:i:s'));
Why are you using echo?  If you want them in the locak log, you should use the CliLog class to stay consistent.

2021-04-26 15:52 UTC, Hobstweedl commented
Updated the code. I was using echo because I am trying to figure out why the notifications aren't getting added to the calendar and just printing info directly to the log file to see if the script was getting to that point. I wouldn't use any echo statements or cli logs otherwise

2021-04-27 14:36 UTC, thehandcoder commented
Sorry I missed this the first time.  You also need to add the item to the configs/pharmacy.crons file so it will run at the proper time.

2021-04-27 14:57 UTC, merged