Comms Calendar Language Translation
dscsa/pharmacy pull request #248
Opened 2021-06-17 15:36 UTC by Hobstweedl

- Adds language to comms array
- New function to find a patient by id and get their set language
- Adds language to all of the event functions

2021-06-17 18:37 UTC, Hobstweedl commented on helpers/helper_calendar.php
> +        $text['language'] = $language;
https://github.com/dscsa/communication-calendar/commit/6f71d1f2f511aaeba5951b365dfe6e5f91cbc45f#diff-d149f09882695561e18e2a89b0097890e128fda4967d74cc09460116e99afb67R149-R153

Based on that snippet I think these objects need a `language` property set

2021-06-23 21:23 UTC, thehandcoder requested changes

2021-06-23 21:23 UTC, thehandcoder commented on helpers/helper_calendar.php
> +function getPatientLanguage(int $patient_id_cp = null) {
I'm kind of confused by this.  Why write a function that creates an object.  Why not just use an object.  Or pass the patient_id_cp into the new_com_array funciton.

You could even make EN the default on the patientclass then do
GpPatient::where('patient_id_cp', $patient_id_cp)->firstOrNew()->getLanguage();

it seems like we are mixing functions and objects vs just trying to push the object to the front of the stack

2021-06-24 15:16 UTC, Hobstweedl commented on helpers/helper_calendar.php
> +function getPatientLanguage(int $patient_id_cp = null) {
The only goal was to get language translations working on emails, I wasn't considering refactoring all of this code. Would you prefer that in https://github.com/dscsa/pharmacy/pull/248/files#diff-4cc96f64a6265d465b07afe4aaabf53c6ab4a63b5a4ef272198e83f4fa3cdc6cR370 instead of a patient label you pass the whole item in, and use the model to generate the patient label and get the language?

2021-06-24 16:34 UTC, merged